version: '3.3'
services:

  jekyll:
    image: jekyll/jekyll:${JEKYLL_VERSION}
    volumes:
      - ./vendor/bundle:/usr/local/bundle
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=production
    command: jekyll build


